<?php
// /partials/github_login.php

// This file should be included on your login.php and register.php pages.



// Ensure the autoloader can find the League OAuth classes
require_once __DIR__ . '/../vendor/autoload.php';

use League\OAuth2\Client\Provider\Github;

// Initialize the provider with credentials from your config file
$provider = new Github([
    'clientId'          => GITHUB_CLIENT_ID,
    'clientSecret'      => GITHUB_CLIENT_SECRET,
    'redirectUri'       => GITHUB_REDIRECT_URL,
]);

// Define the permissions we need. 'user:email' is crucial.
$options = [
    'scope' => ['read:user', 'user:email']
];

// Generate the authorization URL
$github_login_url = $provider->getAuthorizationUrl($options);

// Store the state generated by the library in the session for CSRF protection.
// This is a critical security step.
$_SESSION['oauth2state'] = $provider->getState();
?>